name: pre-commit autoupdate

on:
  # schedule:
  #   - cron: "0 0 * * 1" # Run every Monday at 00:00
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  BRANCH_NAME: chore/pre-commit-autoupdate-workflow

jobs:
  pre-commit-autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          check-latest: true
          cache: "pip"
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
      - name: Cache pre-commit hooks
        id: cache-pre-commit
        uses: actions/cache@v4
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}-${{ env.CACHE_NUMBER }}
      - name: Install pre-commit hooks
        if: steps.cache-pre-commit.outputs.cache-hit != 'true'
        run: |
          pre-commit install
      - name: Update pre-commit hooks
        id: autoupdate-pre-commit
        run: |
          OUTPUT=$(pre-commit autoupdate || echo "autoupdate failed")
          echo "$OUTPUT"
          if [[ "$OUTPUT" == *"No updates available"* ]]; then
            exit 0
          fi
      - name: Test updated pre-commit hooks
        run: |
          if ! pre-commit run --all-files; then
            echo "Pre-commit hooks failed. Please review the log above for details." >&2
            exit 1
          fi
      - name: Push changes and create PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "${{ env.BRANCH_NAME }}"
          sign-commits: true
          title: "chore: autoupdate pre-commit hooks"
          body: |
            This PR updates pre-commit hooks to their latest versions.
          commit-message: "chore(pre-commit): bump hooks"
          delete-branch: true
          base: main
